language: rust
os:
    - linux
    - osx
install:
    - git clone git://github.com/nsf/termbox.git termbox
    - cd termbox
    - ./waf configure --prefix=/usr
    - ./waf
    - ./waf install
before_script:
    - rustc -v
    - cargo -V
script:
    - cargo build -v
    - cargo test -v
