[project]
name = "iota"
version = "0.1.0"
authors = ["Greg Chapple <gregchapple1@gmail.com>"]

[dependencies]
docopt = "0.6.26"
rustbox = "0.2.7"
rustc-serialize = "0.2.7"

[dependencies.gapbuffer]
git = "https://github.com/dlaronson/gapbuffer"
version = "0.0.4"

[lib]
name = "iota"
path = "src/iota/lib.rs"

[[bin]]
name = "iota"
doc = false
