[project]
name = "rdit"
version = "0.1.0"
authors = ["Greg Chapple <gregchapple1@gmail.com>"]

[dependencies.rustbox]
git = "https://github.com/gchp/rustbox.git"

[dependencies.docopt]
git = "git://github.com/docopt/docopt.rs"

[lib]
name = "rdit"
path = "src/rdit/lib.rs"

[[bin]]
name = "rdit"
doc = false
