[project]
name = "rdit"
version = "0.1.0"
authors = ["Greg Chapple <gregchapple1@gmail.com>"]

[dependencies.rustbox]
git = "https://github.com/gchp/rustbox.git"

[[lib]]
name = "rdit"

[[bin]]
name = "rdit"
